# -*- coding: utf-8 -*-
"""Despliegue_Practica_SeleccionFactores_Modelos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MnPoXy_Wo065xBPVNHWXBb_qXfxE1ilN

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-reg-practica.pkl'
modelo, min_max_scaler, variables = pickle.load(open(filename, 'rb'))
#modelo

# Display the variables expected by the model to help with data adaptation
print("Variables expected by the models:")
for var in variables:
    print(var)

#Ya mis datos no sera por archivo sino que por formulario
#Cargamos los datos futuros
#data = pd.read_csv("videojuegos-datosFuturos.csv")
#data.head()

import streamlit as st
import pandas as pd

st.title('Predicción de PUNT_GLOBAL para estudiantes')

# User choice for input method
input_method = st.radio("Seleccione el método de entrada de datos:", ('Ingreso Manual', 'Subir Archivo CSV'))

if input_method == 'Ingreso Manual':
    st.header('Ingreso Manual de Datos')
    PERIODO = st.number_input('PERIODO', min_value=2010, max_value=2024, value=2023, step=1)
    EDAD = st.slider('EDAD', min_value=14, max_value=52, value=20, step=1)
    COLE_AREA_UBICACION = st.selectbox('COLE_AREA_UBICACION', ['RURAL', 'URBANA'])
    COLE_BILINGUE = st.selectbox('COLE_BILINGUE', ['S', 'N'])
    COLE_CARACTER = st.selectbox('COLE_CARACTER', ['ACADÉMICO', 'NO APLICA', 'TÉCNICO', 'TÉCNICO/ACADÉMICO'])
    COLE_JORNADA = st.selectbox('COLE_JORNADA', ['COMPLETA', 'MAÑANA', 'NOCHE', 'SABATINA', 'TARDE', 'UNICA'])
    COLE_MCPIO_UBICACION = st.text_input('COLE_MCPIO_UBICACION', value='BOGOTÁ')
    COLE_NATURALEZA = st.selectbox('COLE_NATURALEZA', ['OFICIAL', 'NO OFICIAL'])
    COLE_SEDE_PRINCIPAL = st.selectbox('COLE_SEDE_PRINCIPAL', ['S', 'N'])
    ESTU_DEPTO_RESIDE = st.text_input('ESTU_DEPTO_RESIDE', value='CUNDINAMARCA')
    ESTU_GENERO = st.selectbox('ESTU_GENERO', ['M', 'F'])
    ESTU_MCPIO_RESIDE = st.text_input('ESTU_MCPIO_RESIDE', value='BOGOTÁ, D.C.')
    ESTU_NACIONALIDAD = st.text_input('ESTU_NACIONALIDAD', value='COLOMBIA')
    ESTU_PAIS_RESIDE = st.text_input('ESTU_PAIS_RESIDE', value='COLOMBIA')
    FAMI_CUARTOSHOGAR = st.selectbox('FAMI_CUARTOSHOGAR', ['Uno', 'Dos', 'Tres', 'Cuatro', 'Cinco o más'])
    FAMI_EDUCACIONMADRE = st.text_input('FAMI_EDUCACIONMADRE', value='Ninguno')
    FAMI_EDUCACIONPADRE = st.text_input('FAMI_EDUCACIONPADRE', value='Ninguno')
    FAMI_ESTRATOVIVIENDA = st.selectbox('FAMI_ESTRATOVIVIENDA', ['Estrato 1', 'Estrato 2', 'Estrato 3', 'Estrato 4', 'Estrato 5', 'Estrato 6', 'Sin Estrato'])
    FAMI_PERSONASHOGAR = st.number_input('FAMI_PERSONASHOGAR', min_value=1, max_value=10, value=3, step=1)
    FAMI_TIENEAUTOMOVIL = st.selectbox('FAMI_TIENEAUTOMOVIL', ['Si', 'No'])
    FAMI_TIENECOMPUTADOR = st.selectbox('FAMI_TIENECOMPUTADOR', ['Si', 'No'])
    FAMI_TIENEINTERNET = st.selectbox('FAMI_TIENEINTERNET', ['Si', 'No'])
    FAMI_TIENELAVADORA = st.selectbox('FAMI_TIENELAVADORA', ['Si', 'No'])

    datos = [[PERIODO, EDAD, COLE_AREA_UBICACION, COLE_BILINGUE, COLE_CARACTER,
              COLE_JORNADA, COLE_MCPIO_UBICACION, COLE_NATURALEZA, COLE_SEDE_PRINCIPAL,
              ESTU_DEPTO_RESIDE, ESTU_GENERO, ESTU_MCPIO_RESIDE, ESTU_NACIONALIDAD,
              ESTU_PAIS_RESIDE, FAMI_CUARTOSHOGAR, FAMI_EDUCACIONMADRE, FAMI_EDUCACIONPADRE,
              FAMI_ESTRATOVIVIENDA, FAMI_PERSONASHOGAR, FAMI_TIENEAUTOMOVIL,
              FAMI_TIENECOMPUTADOR, FAMI_TIENEINTERNET, FAMI_TIENELAVADORA]]

    columns = ['PERIODO', 'EDAD', 'COLE_AREA_UBICACION', 'COLE_BILINGUE', 'COLE_CARACTER',
               'COLE_JORNADA', 'COLE_MCPIO_UBICACION', 'COLE_NATURALEZA', 'COLE_SEDE_PRINCIPAL',
               'ESTU_DEPTO_RESIDE', 'ESTU_GENERO', 'ESTU_MCPIO_RESIDE', 'ESTU_NACIONALIDAD',
               'ESTU_PAIS_RESIDE', 'FAMI_CUARTOSHOGAR', 'FAMI_EDUCACIONMADRE', 'FAMI_EDUCACIONPADRE',
               'FAMI_ESTRATOVIVIENDA', 'FAMI_PERSONASHOGAR', 'FAMI_TIENEAUTOMOVIL',
               'FAMI_TIENECOMPUTADOR', 'FAMI_TIENEINTERNET', 'FAMI_TIENELAVADORA']

    data = pd.DataFrame(datos, columns=columns)

elif input_method == 'Subir Archivo CSV':
    st.header('Subir Archivo CSV')
    uploaded_file = st.file_uploader("Arrastra y suelta tu archivo CSV aquí o haz clic para buscar", type="csv")
    if uploaded_file is not None:
        data = pd.read_csv(uploaded_file)
        st.write("Vista previa de los datos cargados:")
        st.dataframe(data.head())
    else:
        data = pd.DataFrame() # Empty DataFrame if no file uploaded

#Se realiza la preparación de datos

if data.empty:
    st.warning("No hay datos para procesar. Por favor, ingrese datos manualmente o suba un archivo CSV.")
    data_preparada = pd.DataFrame() # Ensure data_preparada is empty if no data
else:
    data_preparada = data.copy()

    #En despliegue drop_first= False
    categorical_cols = [
        'COLE_AREA_UBICACION', 'COLE_BILINGUE', 'COLE_CARACTER', 'COLE_JORNADA',
        'COLE_MCPIO_UBICACION', 'COLE_NATURALEZA', 'COLE_SEDE_PRINCIPAL',
        'ESTU_DEPTO_RESIDE', 'ESTU_GENERO', 'ESTU_MCPIO_RESIDE',
        'ESTU_NACIONALIDAD', 'ESTU_PAIS_RESIDE', 'FAMI_CUARTOSHOGAR',
        'FAMI_EDUCACIONMADRE', 'FAMI_EDUCACIONPADRE', 'FAMI_ESTRATOVIVIENDA',
        'FAMI_TIENEAUTOMOVIL', 'FAMI_TIENECOMPUTADOR', 'FAMI_TIENEINTERNET', 'FAMI_TIENELAVADORA'
    ]

    # Filter categorical_cols to only include those actually present in data_preparada
    cols_to_get_dummies = [col for col in categorical_cols if col in data_preparada.columns]

    if len(cols_to_get_dummies) < len(categorical_cols):
        missing_cols = set(categorical_cols) - set(cols_to_get_dummies)
        st.error(f"Error en la preparación de datos: Las siguientes columnas categóricas esperadas no se encontraron en los datos de entrada: {missing_cols}. Asegúrese de que los nombres de las columnas en su CSV (si aplica) o en la entrada manual coinciden con el modelo.")
    else:
        st.info("Todas las columnas categóricas necesarias están presentes para el procesamiento.")

    data_preparada = pd.get_dummies(data_preparada, columns=cols_to_get_dummies, drop_first=False, dtype=int)

#Se adicionan las columnas faltantes
if not data_preparada.empty:
    data_preparada = data_preparada.reindex(columns=variables, fill_value=0)
    # st.write("Datos preparados para el modelo:")
    # st.dataframe(data_preparada.head()) # Optional: display prepared data for debugging
else:
    st.warning("No se puede reindexar: la trama de datos preparada está vacía.")

#Se normaliza la edad para predecir con Knn, Red, SVM, Reg
#En los despliegues no se llama fit
# La columna 'PUNT_GLOBAL' no debe estar presente en los datos de entrada para la predicción.
# Si el modelo predice valores escalados, el min_max_scaler se debe usar para el inverse_transform de las predicciones.
# data_preparada[['PUNT_GLOBAL']]= min_max_scaler.transform(data_preparada[['PUNT_GLOBAL']])
# data_preparada.head()

"""# **Predicciones**"""

#Hacemos la predicción con el modelo
if not data_preparada.empty:
    try:
        Y_pred = modelo.predict(data_preparada)
        st.subheader("Predicciones Generadas:")
        # Optional: Display raw predictions
        # st.write(Y_pred)
    except Exception as e:
        st.error(f"Error al realizar la predicción: {e}")
        Y_pred = None # Ensure Y_pred is set to None on error
else:
    st.warning("No se puede realizar la predicción: la trama de datos preparada está vacía.")
    Y_pred = None # Ensure Y_pred is defined even if empty

if not data.empty and Y_pred is not None and len(Y_pred) == len(data):
    data['Prediccion'] = Y_pred
    st.subheader("Datos de entrada con Predicciones:")
    st.dataframe(data)
else:
    if data.empty:
        st.warning("No hay datos originales para adjuntar predicciones.")
    elif Y_pred is None:
        st.warning("No se generaron predicciones.")
    else:
        st.warning("Error: El número de predicciones no coincide con el número de filas de datos de entrada.")

# Opciones de descarga y visualización de predicciones
import matplotlib.pyplot as plt
import seaborn as sns

if not data.empty and 'Prediccion' in data.columns:
    st.subheader("Descargar Predicciones")
    csv = data.to_csv(index=False).encode('utf-8')
    st.download_button(
        label="Descargar Predicciones como CSV",
        data=csv,
        file_name='predicciones_PUNT_GLOBAL.csv',
        mime='text/csv',
    )

    # --- Visualización de Predicciones ---
    st.subheader("Visualización de Predicciones")

    # Histograma de las predicciones
    fig1, ax1 = plt.subplots(figsize=(10, 6))
    sns.histplot(data['Prediccion'], kde=True, ax=ax1)
    ax1.set_title('Distribución de las Predicciones de PUNT_GLOBAL')
    ax1.set_xlabel('PUNT_GLOBAL Predicho')
    ax1.set_ylabel('Frecuencia')
    st.pyplot(fig1)

    # Si hay suficientes datos y variables categóricas, se pueden añadir más gráficos
    if len(data) > 1 and 'FAMI_ESTRATOVIVIENDA' in data.columns:
        fig2, ax2 = plt.subplots(figsize=(10, 6))
        sns.boxplot(x='FAMI_ESTRATOVIVIENDA', y='Prediccion', data=data, ax=ax2)
        ax2.set_title('Predicción de PUNT_GLOBAL por Estrato de Vivienda')
        ax2.set_xlabel('Estrato de Vivienda')
        ax2.set_ylabel('PUNT_GLOBAL Predicho')
        plt.xticks(rotation=45)
        st.pyplot(fig2)

    if len(data) > 1 and 'COLE_NATURALEZA' in data.columns:
        fig3, ax3 = plt.subplots(figsize=(10, 6))
        sns.barplot(x='COLE_NATURALEZA', y='Prediccion', data=data, ax=ax3)
        ax3.set_title('Predicción de PUNT_GLOBAL por Naturaleza del Colegio')
        ax3.set_xlabel('Naturaleza del Colegio')
        ax3.set_ylabel('PUNT_GLOBAL Predicho')
        st.pyplot(fig3)

else:
    st.info("No hay predicciones disponibles para descargar o visualizar. Por favor, genere predicciones primero.")

# Recordar medida de error del modelo

st.warning("Xgboost MAE de la CV -29.14687")