# -*- coding: utf-8 -*-
"""Despliegue_Practica_SeleccionFactores_Modelos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MnPoXy_Wo065xBPVNHWXBb_qXfxE1ilN

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-reg-practica.pkl'
modelo, min_max_scaler, variables = pickle.load(open(filename, 'rb'))
#modelo

# Display the variables expected by the model to help with data adaptation
print("Variables expected by the models:")
for var in variables:
    print(var)

#Ya mis datos no sera por archivo sino que por formulario
#Cargamos los datos futuros
#data = pd.read_csv("videojuegos-datosFuturos.csv")
#data.head()

#Interfaz gráfica


#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de PUNT_GLOBAL para estudiantes')

PERIODO = st.number_input('PERIODO', min_value=2010, max_value=2024, value=2023, step=1)
EDAD = st.slider('EDAD', min_value=14, max_value=52, value=20, step=1)
COLE_AREA_UBICACION = st.selectbox('COLE_AREA_UBICACION', ['RURAL', 'URBANA'])
COLE_BILINGUE = st.selectbox('COLE_BILINGUE', ['S', 'N'])
COLE_CARACTER = st.selectbox('COLE_CARACTER', ['ACADÉMICO', 'NO APLICA', 'TÉCNICO', 'TÉCNICO/ACADÉMICO'])
COLE_JORNADA = st.selectbox('COLE_JORNADA', ['COMPLETA', 'MAÑANA', 'NOCHE', 'SABATINA', 'TARDE', 'UNICA'])
COLE_MCPIO_UBICACION = st.text_input('COLE_MCPIO_UBICACION', value='BOGOTÁ') # Please adjust options based on your data
COLE_NATURALEZA = st.selectbox('COLE_NATURALEZA', ['OFICIAL', 'NO OFICIAL'])
COLE_SEDE_PRINCIPAL = st.selectbox('COLE_SEDE_PRINCIPAL', ['S', 'N'])
ESTU_DEPTO_RESIDE = st.text_input('ESTU_DEPTO_RESIDE', value='CUNDINAMARCA') # Please adjust options based on your data
ESTU_GENERO = st.selectbox('ESTU_GENERO', ['M', 'F'])
ESTU_MCPIO_RESIDE = st.text_input('ESTU_MCPIO_RESIDE', value='BOGOTÁ, D.C.') # Please adjust options based on your data
ESTU_NACIONALIDAD = st.text_input('ESTU_NACIONALIDAD', value='COLOMBIA') # Please adjust options based on your data
ESTU_PAIS_RESIDE = st.text_input('ESTU_PAIS_RESIDE', value='COLOMBIA') # Please adjust options based on your data
FAMI_CUARTOSHOGAR = st.selectbox('FAMI_CUARTOSHOGAR', ['Uno', 'Dos', 'Tres', 'Cuatro', 'Cinco o más']) # Please adjust options based on your data
FAMI_EDUCACIONMADRE = st.text_input('FAMI_EDUCACIONMADRE', value='Ninguno') # Please adjust options based on your data
FAMI_EDUCACIONPADRE = st.text_input('FAMI_EDUCACIONPADRE', value='Ninguno') # Please adjust options based on your data
FAMI_ESTRATOVIVIENDA = st.selectbox('FAMI_ESTRATOVIVIENDA', ['Estrato 1', 'Estrato 2', 'Estrato 3', 'Estrato 4', 'Estrato 5', 'Estrato 6', 'Sin Estrato']) # Please adjust options based on your data
FAMI_PERSONASHOGAR = st.number_input('FAMI_PERSONASHOGAR', min_value=1, max_value=10, value=3, step=1)
FAMI_TIENEAUTOMOVIL = st.selectbox('FAMI_TIENEAUTOMOVIL', ['Si', 'No'])
FAMI_TIENECOMPUTADOR = st.selectbox('FAMI_TIENECOMPUTADOR', ['Si', 'No'])
FAMI_TIENEINTERNET = st.selectbox('FAMI_TIENEINTERNET', ['Si', 'No'])
FAMI_TIENELAVADORA = st.selectbox('FAMI_TIENELAVADORA', ['Si', 'No'])


#Dataframe
datos = [[PERIODO, EDAD, COLE_AREA_UBICACION, COLE_BILINGUE, COLE_CARACTER,
          COLE_JORNADA, COLE_MCPIO_UBICACION, COLE_NATURALEZA, COLE_SEDE_PRINCIPAL,
          ESTU_DEPTO_RESIDE, ESTU_GENERO, ESTU_MCPIO_RESIDE, ESTU_NACIONALIDAD,
          ESTU_PAIS_RESIDE, FAMI_CUARTOSHOGAR, FAMI_EDUCACIONMADRE, FAMI_EDUCACIONPADRE,
          FAMI_ESTRATOVIVIENDA, FAMI_PERSONASHOGAR, FAMI_TIENEAUTOMOVIL,
          FAMI_TIENECOMPUTADOR, FAMI_TIENEINTERNET, FAMI_TIENELAVADORA]]

columns = ['PERIODO', 'EDAD', 'COLE_AREA_UBICACION', 'COLE_BILINGUE', 'COLE_CARACTER',
           'COLE_JORNADA', 'COLE_MCPIO_UBICACION', 'COLE_NATURALEZA', 'COLE_SEDE_PRINCIPAL',
           'ESTU_DEPTO_RESIDE', 'ESTU_GENERO', 'ESTU_MCPIO_RESIDE', 'ESTU_NACIONALIDAD',
           'ESTU_PAIS_RESIDE', 'FAMI_CUARTOSHOGAR', 'FAMI_EDUCACIONMADRE', 'FAMI_EDUCACIONPADRE',
           'FAMI_ESTRATOVIVIENDA', 'FAMI_PERSONASHOGAR', 'FAMI_TIENEAUTOMOVIL',
           'FAMI_TIENECOMPUTADOR', 'FAMI_TIENEINTERNET', 'FAMI_TIENELAVADORA']

data = pd.DataFrame(datos, columns=columns) #Dataframe con los mismos nombres de variables

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
categorical_cols = [
    'COLE_AREA_UBICACION', 'COLE_BILINGUE', 'COLE_CARACTER', 'COLE_JORNADA',
    'COLE_MCPIO_UBICACION', 'COLE_NATURALEZA', 'COLE_SEDE_PRINCIPAL',
    'ESTU_DEPTO_RESIDE', 'ESTU_GENERO', 'ESTU_MCPIO_RESIDE',
    'ESTU_NACIONALIDAD', 'ESTU_PAIS_RESIDE', 'FAMI_CUARTOSHOGAR',
    'FAMI_EDUCACIONMADRE', 'FAMI_EDUCACIONPADRE', 'FAMI_ESTRATOVIVIENDA',
    'FAMI_TIENEAUTOMOVIL', 'FAMI_TIENECOMPUTADOR', 'FAMI_TIENEINTERNET', 'FAMI_TIENELAVADORA'
]
data_preparada = pd.get_dummies(data_preparada, columns=categorical_cols, drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red, SVM, Reg
#En los despliegues no se llama fit
# La columna 'PUNT_GLOBAL' no debe estar presente en los datos de entrada para la predicción.
# Si el modelo predice valores escalados, el min_max_scaler se debe usar para el inverse_transform de las predicciones.
# data_preparada[['PUNT_GLOBAL']]= min_max_scaler.transform(data_preparada[['PUNT_GLOBAL']])
# data_preparada.head()

"""# **Predicciones**"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

#Predicciones finales
data

# Recordar medida de error del modelo

st.warning("Xgboost MAE de la CV -29.14687")